# Generated by Django 3.1.1 on 2022-12-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='Modelnumber',
        ),
        migrations.AddField(
            model_name='laptop',
            name='Modelname',
            field=models.CharField(default=3, max_length=80),
            preserve_default=False,
        ),
    ]
